CREATE TABLE user_category_feedback
(
    user_category_feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id                   BIGINT                                  NOT NULL,
    category_name             VARCHAR(255)                            NOT NULL,
    like_status               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_category_feedback PRIMARY KEY (user_category_feedback_id)
);

ALTER TABLE travel_outfit_recommendation
    ADD error_message VARCHAR(500);

ALTER TABLE travel_outfit_recommendation
    ADD safety_notes_json JSONB;

ALTER TABLE travel_outfit_recommendation
    ADD status VARCHAR(20);

ALTER TABLE travel_outfit_recommendation
    ADD umbrella_summary VARCHAR(1000);

ALTER TABLE user_category_feedback
    ADD CONSTRAINT user_category_unique UNIQUE (user_id, category_name);

ALTER TABLE user_category_feedback
    ADD CONSTRAINT FK_USER_CATEGORY_FEEDBACK_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);