-- Flyway 베이스라인 스크립트
-- 기존 DB 스키마를 정의합니다.

-- 1. Product Table
create table product
(
    product_id   bigint generated by default as identity
        primary key,
    category     varchar(255),
    name         varchar(255),
    sub_category varchar(255)
);

create table product_style_tags
(
    product_id bigint not null
        constraint fk7sf56xhqt14hsfrb53t3ieugq
            references product,
    style_tag  varchar(255)
);

-- 2. Region Grid Table
create table region_grid
(
    latitude        double precision,
    longitude       double precision,
    region_id       bigint not null
        primary key,
    region_city     varchar(255),
    region_district varchar(255),
    region_province varchar(255)
);

-- 3. Users Table
create table users
(
    email_verified   boolean      not null,
    created_at       timestamp(6) not null,
    deleted_at       timestamp(6),
    updated_at       timestamp(6) not null,
    user_id          bigint generated by default as identity
        primary key,
    nickname         varchar(30)  not null,
    style_preference varchar(30),
    email            varchar(100) not null
        unique,
    provider_id      varchar(100),
    gender           varchar(255)
        constraint users_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    password         varchar(255) not null,
    provider         varchar(255)
        constraint users_provider_check
            check ((provider)::text = ANY ((ARRAY ['LOCAL'::character varying, 'GOOGLE'::character varying])::text[])),
    role             varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[]))
);

-- 4. Travel Outfit Recommendation Table
create table travel_outfit_recommendation
(
    avg_humidity              integer,
    avg_temperature           double precision,
    end_date                  date         not null,
    rain_probability          integer,
    start_date                date         not null,
    created_at                timestamp(6) not null,
    travel_outfit_id          bigint generated by default as identity
        primary key,
    updated_at                timestamp(6) not null,
    user_id                   bigint,
    status                    varchar(20)
        constraint travel_outfit_recommendation_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    city                      varchar(100) not null,
    country                   varchar(100) not null,
    error_message             varchar(500),
    umbrella_summary          varchar(1000),
    condition                 varchar(255),
    ai_outfit_json            jsonb,
    cultural_constraints_json jsonb,
    safety_notes_json         jsonb
);

-- 5. Posts Table
create table posts
(
    like_count  integer      not null,
    share_count integer      not null,
    created_at  timestamp(6) not null,
    deleted_at  timestamp(6),
    post_id     bigint generated by default as identity
        primary key,
    updated_at  timestamp(6) not null,
    user_id     bigint       not null
        constraint fk5lidm6cqbc7u4xhqpxm898qme
            references users,
    version     bigint,
    title       varchar(100) not null,
    content     text         not null
);

-- 6. Post Likes Table
create table post_likes
(
    like_id bigint generated by default as identity
        primary key,
    post_id bigint not null
        constraint fka5wxsgl4doibhbed9gm7ikie2
            references posts,
    user_id bigint not null
        constraint fkkgau5n0nlewg6o9lr4yibqgxj
            references users,
    unique (post_id, user_id)
);

-- 7. Post Shares Table
create table post_shares
(
    post_id  bigint      not null
        constraint fkaqcgoc82dbvm91c4s6ybp0d80
            references posts,
    share_id bigint generated by default as identity
        primary key,
    user_id  bigint      not null
        constraint fkhrf6mxii6ey1akrwfd5xwp85c
            references users,
    platform varchar(30) not null
);

-- 8. User Category Feedback Table
create table user_category_feedback
(
    created_at                timestamp(6) not null,
    updated_at                timestamp(6) not null,
    user_category_feedback_id bigint generated by default as identity
        primary key,
    user_id                   bigint       not null
        constraint fkh4msiy9794givu4pjadvo3y0h
            references users,
    category_name             varchar(255) not null,
    like_status               varchar(255) not null
        constraint user_category_feedback_like_status_check
            check ((like_status)::text = ANY
                   ((ARRAY ['LIKE'::character varying, 'DISLIKE'::character varying])::text[])),
    constraint user_category_unique
        unique (user_id, category_name)
);

-- 9. User Item Feedback Table
create table user_item_feedback
(
    created_at            timestamp(6) not null,
    product_id            bigint       not null
        constraint fkl341a6flwq53yx4q1jphvomtt
            references product,
    updated_at            timestamp(6) not null,
    user_id               bigint       not null
        constraint fk8ia2ubkpecqmj0w29askoraat
            references users,
    user_item_feedback_id bigint generated by default as identity
        primary key,
    like_status           varchar(255) not null
        constraint user_item_feedback_like_status_check
            check ((like_status)::text = ANY
                   ((ARRAY ['LIKE'::character varying, 'DISLIKE'::character varying])::text[])),
    constraint user_item_unique
        unique (user_id, product_id)
);

-- 10. Weather Table
create table weather
(
    humidity      double precision,
    rainfall      double precision,
    temperature   double precision,
    wind_speed    double precision,
    forecast_time timestamp(6),
    region_id     bigint
        constraint fkglma0p1nwe4jaxhoal2muwtiw
            references region_grid,
    weather_id    bigint generated by default as identity
        primary key
);